In [6]:
import string
import igraph
import numpy as np
import pandas as pd
import csv
import random
#Fast dynamic time warping
from scipy.spatial.distance import euclidean
from fastdtw import fastdtw


#import sys
#np.set_printoptions(threshold=sys.maxsize)

### DATASET 1


In [7]:
#placing the values in a 2D list 
# can create an array of lists by np.array(mlist1)

length = 0
mlist1 = []
for line in open("data1_Main_timeSeries.csv"):
        reader_file = csv.reader(open("data1_Main_timeSeries.csv"))
        length_of_file = len(list(reader_file))
        x = line.split(',')
        y = []
        for i in range(len(x)):
            y.append(float(x[i]))
            #mlist.append(float(x[i]))
        mlist1.append(y)
        length = max(length, len(y))
        arr = np.array(mlist1)
length
#mlist1

0

In [8]:
#padding 0s at the end of the arrays
arr_of_arr= []
li_padded = []
for i in range(0,len(arr)):
    abc = np.array(mlist1[i])
    a_padded = np.pad(abc,(0,length-len(mlist1[i])),'constant')
    #a_stack = np.stack(a_padded, axis=0)
    #arr_of_arr = np.append(arr_of_arr,a_padded,axis = 0) # contains a 1D array with all the values.
    #ar_splited = np.split(arr_of_arr,[length]*i)
    li_padded.append(a_padded)

    
print ((li_padded))    
#print (arr_of_arr[0:length+length])
#print(len(a_padded))

NameError: name 'arr' is not defined

### DATASET 2

In [128]:
#placing the values in a 2D list 
# can create an array of lists by np.array(mlist1)

length2 = 0
mlist2 = []
for line in open("data2_Main_timeSeries.csv"):
        reader_file2 = csv.reader(open("data2_Main_timeSeries.csv"))
        length_of_file2 = len(list(reader_file2))
        x2 = line.split(',')
        y2 = []
        for i in range(len(x2)):
            y2.append(float(x2[i]))
            #mlist.append(float(x[i]))
        mlist2.append(y2)
        length2 = max(length2, len(y2))
        arr2 = np.array(mlist2)

length2
print (mlist2[0])

[7.5, -2.5, 2.5, -7.5, 0.5, -5.5, -0.5, 7.5, 8.5, -6.5, 8.5, 0.5, 5.5, -8.5, -5.5, 4.5, -0.5, 0.0, -10.5, 5.5, -5.5]


In [100]:
#padding 0s at the end of the arrays (padding  for dataset 2 is not required, but i still it did it anyway ¯\_(ツ)_/¯ )
# 0 values are spaces
arr_of_arr2= []
li_padded2 = []
for i in range(0,len(arr2)):
    abc2 = np.array(mlist2[i])
    a_padded2 = np.pad(abc2,(0,length2-len(mlist2[i])),'constant')
    #a_stack = np.stack(a_padded, axis=0)
    #arr_of_arr = np.append(arr_of_arr,a_padded,axis = 0) # contains a 1D array with all the values.
    #ar_splited = np.split(arr_of_arr,[length]*i)
    li_padded2.append(a_padded2)

    
print ((li_padded2[2]))  #this is silimar to element[14]
print ((li_padded2[12]))
#print (arr_of_arr[0:length+length])
#print(len(a_padded))

[  7.5   6.5  -2.5  -8.5  -5.5  -8.5   5.5   7.5   8.5   8.5  -1.5  -7.5
 -10.5   4.5  -5.5 -10.5  -0.5  -2.5 -10.5   4.5   2.5]
[  7.5   6.5  -2.5  -8.5  -5.5  -7.5   5.5   7.5   8.5   8.5  -1.5  -7.5
 -10.5   4.5  -5.5   4.5  -0.5  -2.5 -10.5   0.5   2.5]


### Fast Dynamic time warping


In [101]:
#test
x = np.array([[1,1], [2,2], [3,3], [4,4], [5,5]])
y = np.array([[2,2], [3,3], [4,4]])
distance, path = fastdtw(x, y, dist=euclidean)
print(distance)

2.8284271247461903


In [102]:
#data1
distance, path = fastdtw(li_padded[0],li_padded[2],dist=euclidean)
print (distance)

24.0


In [104]:
#data1
#changes from G to D 
distance, path = fastdtw(li_padded[2],li_padded[1],dist=euclidean)
print (distance)

3.0


In [105]:
#data2
distance2, path2 = fastdtw(li_padded2[0],li_padded2[14],dist=euclidean)
print (distance2)

9.0


In [106]:
#data2
distance2, path2 = fastdtw(li_padded2[2],li_padded2[12],dist=euclidean)
print (distance2)

15.0


### Difflib SequenceMatcher 

In [107]:
from difflib import SequenceMatcher

In [108]:
s1=[1,8,3,9,4,9,3,8,1,2,3]
s2=[1,8,1,3,9,4,9,3,8,1,2,3]
sm=SequenceMatcher(None,s1,s2)
sm.ratio()

0.9565217391304348

In [109]:
sm_data1_test1 = SequenceMatcher(None,li_padded[0],li_padded[2],)
sm_data1_test1.ratio()

0.8709677419354839

In [110]:
sm_data1_test2 = SequenceMatcher(None,li_padded[2],li_padded[1],)
sm_data1_test2.ratio()

0.967741935483871

In [111]:
sm_data2 = SequenceMatcher(None, "WKQENGMWYFYNTDGSM ALG","WKQENGMWYFYNTDGSM AIG")
sm_data2.ratio()*100

95.23809523809523

In [112]:
sm_data2_test2 = SequenceMatcher(None,li_padded2[2],li_padded2[12],)
sm_data2_test2.ratio()*100

85.71428571428571

In [114]:
li_padded2[1]

array([  7.5,  -1.5,   2.5,   0.5,   0.5,  -5.5,   4.5,   7.5,   8.5,
         8.5,  -1.5,   0.5, -10.5,   0.5,  -5.5,   4.5,  -0.5,   0. ,
       -10.5,   5.5,  -5.5])

In [115]:
sm_data2 = SequenceMatcher(None, "ADGSSASGESSVSGQSEASTSS","ADSSSAGGQQQESSVSSQSDQASTSSQLG")
sm_data2.ratio()*100

70.58823529411765

In [118]:
sm_data2_test1 = SequenceMatcher(None,li_padded2[0],li_padded2[14],)
sm_data2_test1.ratio()*100

95.23809523809523

In [119]:
# Actual data line1= WKQENGMWYFYNTDGSM ATG and line2 = WKQENGMWYFYNTDGSM AIG
#line1 = "6.5,0.5,-4.5,-5.5,-8.5,-3.5,1.5,6.5,7.5,2.5,7.5,-8.5,5.5,-7.5,-3.5,4.5,1.5,0,-10.5,5.5,-3.5"
#line2= "6.5,0.5,-4.5,-5.5,-8.5,-3.5,1.5,6.5,7.5,2.5,7.5,-8.5,5.5,-7.5,-3.5,4.5,1.5,0,-10.5,-1.5,-3.5"
# >> 98.36065573770492

line1 = "6.5 0.5 -4.5 -5.5 -8.5 -3.5 1.5 6.5 7.5 2.5 7.5 -8.5 5.5 -7.5 -3.5 4.5 1.5 0 -10.5 5.5 -3.5"
line2 = "6.5 0.5 -4.5 -5.5 -8.5 -3.5 1.5 6.5 7.5 2.5 7.5 -8.5 5.5 -7.5 -3.5 4.5 1.5 0 -10.5 -1.5 -3.5"
#>> 98.36065573770492
sm_data2 = SequenceMatcher(None, line1,line2)
sm_data2.ratio()*100

98.36065573770492

In [120]:
# chanegd ATG to ALG and compared to AIG
line11 = "6.5,0.5,-4.5,-5.5,-8.5,-3.5,1.5,6.5,7.5,2.5,7.5,-8.5,5.5,-7.5,-3.5,4.5,1.5,0.,-10.5,-0.5,-3.5"
line21= "6.5,0.5,-4.5,-5.5,-8.5,-3.5,1.5,6.5,7.5,2.5,7.5,-8.5,5.5,-7.5,-3.5,4.5,1.5,0.,-10.5,-1.5,-3.5"
sm_data2 = SequenceMatcher(None, line11,line21)
sm_data2.ratio()*100

98.9247311827957

In [121]:
#line 18 and 19
#line18 = WLEYNGSWYYLNANGAM ATG
#line19 = WLEYNGSWYYLNSNGAM ATG
sm_data2_test3 = SequenceMatcher(None,li_padded2[18],li_padded2[19],)
sm_data2_test3.ratio()*100


95.23809523809523

In [122]:
li_padded2[0]

array([  7.5,  -2.5,   2.5,  -7.5,   0.5,  -5.5,  -0.5,   7.5,   8.5,
        -6.5,   8.5,   0.5,   5.5,  -8.5,  -5.5,   4.5,  -0.5,   0. ,
       -10.5,   5.5,  -5.5])

In [123]:
li_padded2[14]

array([  7.5,  -2.5,   2.5,  -7.5,   0.5,  -5.5,  -0.5,   7.5,   8.5,
        -6.5,   8.5,   0.5,   5.5,  -8.5,  -5.5,   4.5,  -0.5,   0. ,
       -10.5,  -3.5,  -5.5])

In [124]:
# lines 18 and 19 in data 2
line18 = "6.5,-0.5,-5.5,7.5,-8.5,-3.5,4.5,6.5,7.5,7.5,-0.5,-8.5,-10.5,-8.5,-3.5,-10.5,1.5,0.,-10.5,5.5,-3.5"
line19 = "6.5,-0.5,-5.5,7.5,-8.5,-3.5,4.5,6.5,7.5,7.5,-0.5,-8.5,4.5,-8.5,-3.5,-10.5,1.5,0.,-10.5,5.5,-3.5"
sm_data2 = SequenceMatcher(None, line18,line19)
sm_data2.ratio()*100

97.91666666666666

In [126]:
#testing with 5 value changes
line18 = "-6.5,-1.5,-5.5,7.5,-8.5,-3.5,4.5,6.5,5.5,7.5,-0.5,-8.5,-10.5,-8.5,-3.5,-10.5,1.5,0.,-10.5,5.5,-10.5"
line19 = "6.5,-0.5,-5.5,7.5,-8.5,-3.5,4.5,6.5,7.5,7.5,-0.5,-8.5,4.5,-8.5,-3.5,-10.5,1.5,0.,-10.5,5.5,-3.5"
sm_data2 = SequenceMatcher(None, line18,line19)
sm_data2.ratio()*100

93.81443298969072